version: 0.2

phases:
  pre_build:
    commands:
      - echo "Instalando Python 3"
      - sudo apt install python3
      - echo "Instalando Dependencias"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Corriendo Test"
      - python manage.py test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/var/cache/apt/archives/**/*'
    - '/var/lib/apt/lists/**/*'
    - '/etc/apt/sources.list.d/mysql.list'
