version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in Docker"
      - docker login -u=$DOCKER_USER -p=$DOCKER_TOKEN
  build:
    commands:
      - echo "Building Image"
      - docker build . -t $DOCKER_USER/accidentesaereos-backend:latest
  post_build:
    commands:
      - echo "Uploading Image"
      - docker push $DOCKER_USER/accidentesaereos-backend:latest

