version: 0.2

phases:
  pre_build:
    commands:
      - echo "Instalando Python 3"
      - apt install python3
      - echo "Instalando Dependencias"
      - pip install -r requeriments.txt
  build:
    commands:
      - echo "Corriendo Test"
      - python manage.py test
  post_build:
    commands:
      - python manage.py runserver
artifacts:
  files:
    - '**/*'

